In [1]:
!pip install apyori

Requirement already satisfied: apyori in /Users/orvenllantos/Code/Graph/gclass/lib/python3.9/site-packages (1.1.2)

In [2]:
#Importing pandas library to read CSV data file
import pandas as pd

# Data Preprocessing
dataset = pd.read_csv('GroceryStoreDataSet.csv', header = None)

In [3]:
dataset

         0       1       2       3       4
0   coffee   donut   sugar   bread    soup
1     soda   candy    milk  cheese     NaN
2    fruit   bread   cream     NaN     NaN
3   coffee   donut     NaN     NaN     NaN
4    water    soup    milk     NaN     NaN
..     ...     ...     ...     ...     ...
95    milk     NaN     NaN     NaN     NaN
96    soda   candy     NaN     NaN     NaN
97   donut   water  cheese   cream  coffee
98     jam    cake   bread     NaN     NaN
99   cream  coffee   suger   donut     NaN

[100 rows x 5 columns]

In [4]:
transactions = []

for i in range(0, 100):
    transactions.append([str(dataset.values[i,j]) for j in range(0, 5)])

In [5]:
transactions

[['coffee', 'donut', 'sugar', 'bread', 'soup'],
 ['soda', 'candy', 'milk', 'cheese', 'nan'],
 ['fruit', 'bread', 'cream', 'nan', 'nan'],
 ['coffee', 'donut', 'nan', 'nan', 'nan'],
 ['water', 'soup', 'milk', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['coffee', 'sugar', 'donut', 'cheese', 'soda'],
 ['water', 'bread', 'cream', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['coffee', 'cream', 'cheese', 'soup', 'soda'],
 ['water', 'cake', 'cream', 'soda', 'nan'],
 ['soda', 'cake', 'milk', 'candy', 'nan'],
 ['coffee', 'sugar', 'donut', 'nan', 'nan'],
 ['fruit', 'cream', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'cheese', 'nan', 'nan'],
 ['water', 'bread', 'nan', 'nan', 'nan'],
 ['coffee', 'cream', 'sugar', 'soda', 'nan'],
 ['water', 'bread', 'soup', 'nan', 'nan'],
 ['soda', 'candy', 'milk', 'nan', 'nan'],
 ['soda', 'candy', 'cheese', 'nan', 'nan'],
 ['coffee', 'cream', 'donut', 'nan', 'nan'],
 ['soda', 'bread', 'nuts', 'nan', 'nan'],
 ['soda', 'cake', 'soup', 'candy', 'nan'],
 ['jam', 'cake', 'bread', 'nan', 'nan'],
 ['coffee', 'donut', 'nan', 'nan', 'nan'],
 ['jam', 'cheese', 'bread', 'soda', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['soda', 'cake', 'milk', 'cheese', 'bread'],
 ['soda', 'cake', 'soup', 'nan', 'nan'],
 ['water', 'cake', 'nan', 'nan', 'nan'],
 ['coffee', 'donut', 'bread', 'soda', 'nan'],
 ['milk', 'cream', 'nan', 'nan', 'nan'],
 ['soda', 'milk', 'candy', 'nan', 'nan'],
 ['milk', 'cake', 'nan', 'nan', 'nan'],
 ['coffee', 'sugar', 'soup', 'donut', 'nan'],
 ['bread', 'cheese', 'jam', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['bread', 'cake', 'jam', 'nan', 'nan'],
 ['bread', 'milk', 'water', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['soda', 'cream', 'bread', 'nan', 'nan'],
 ['water', 'cheese', 'nan', 'nan', 'nan'],
 ['coffee', 'soup', 'donut', 'nan', 'nan'],
 ['jam', 'water', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['donut', 'milk', 'bread', 'coffee', 'nan'],
 ['fruit', 'cake', 'nan', 'nan', 'nan'],
 ['jam', 'soda', 'soup', 'nan', 'nan'],
 ['sugar', 'coffee', 'nan', 'nan', 'nan'],
 ['cream', 'sugar', 'nan', 'nan', 'nan'],
 ['soda', 'cheese', 'candy', 'nan', 'nan'],
 ['sugar', 'milk', 'nan', 'nan', 'nan'],
 ['coffee', 'soda', 'sugar', 'donut', 'nan'],
 ['milk', 'cake', 'nan', 'nan', 'nan'],
 ['water', 'bread', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'soup', 'nan', 'nan'],
 ['soda', 'bread', 'candy', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['coffee', 'soup', 'donut', 'nan', 'nan'],
 ['donut', 'cheese', 'soda', 'nan', 'nan'],
 ['water', 'milk', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['nuts', 'soup', 'soda', 'nan', 'nan'],
 ['fruit', 'milk', 'nan', 'nan', 'nan'],
 ['nuts', 'water', 'nan', 'nan', 'nan'],
 ['coffee', 'cheese', 'donut', 'nan', 'nan'],
 ['nuts', 'cake', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['sugar', 'candy', 'soup', 'nan', 'nan'],
 ['coffee', 'sugar', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['jam', 'bread', 'cream', 'nan', 'nan'],
 ['coffee', 'donut', 'milk', 'cake', 'nan'],
 ['nuts', 'water', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['nuts', 'water', 'candy', 'nan', 'nan'],
 ['water', 'soup', 'nan', 'nan', 'nan'],
 ['coffee', 'donut', 'sugar', 'nan', 'nan'],
 ['nuts', 'cheese', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'milk', 'nan', 'nan'],
 ['jam', 'bread', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['coffee', 'cream', 'cake', 'nan', 'nan'],
 ['donut', 'water', 'coffee', 'nan', 'nan'],
 ['soda', 'cream', 'candy', 'nan', 'nan'],
 ['jam', 'bread', 'milk', 'nan', 'nan'],
 ['coffee', 'donut', 'cheese', 'nan', 'nan'],
 ['nuts', 'nan', 'nan', 'nan', 'nan'],
 ['soda', 'water', 'cake', 'nan', 'nan'],
 ['fruit', 'soup', 'nan', 'nan', 'nan'],
 ['water', 'nan', 'nan', 'nan', 'nan'],
 ['coffee', 'donut', 'nan', 'nan', 'nan'],
 ['milk', 'nan', 'nan', 'nan', 'nan'],
 ['soda', 'candy', 'nan', 'nan', 'nan'],
 ['donut', 'water', 'cheese', 'cream', 'coffee'],
 ['jam', 'cake', 'bread', 'nan', 'nan'],
 ['cream', 'coffee', 'suger', 'donut', 'nan']]

In [6]:
from apyori import apriori

# Training Apriori on the dataset
rules = apriori(transactions, min_support = 0.08, min_confidence = 0.7, min_lift = 3, min_length = 2,
               max_length = 3)

# Create list of results
results = list(rules)

In [7]:
results

[RelationRecord(items=frozenset({'bread', 'jam'}), support=0.08, ordered_statistics=[OrderedStatistic(items_base=frozenset({'jam'}), items_add=frozenset({'bread'}), confidence=0.7999999999999999, lift=3.8095238095238093)]),
 RelationRecord(items=frozenset({'donut', 'coffee'}), support=0.2, ordered_statistics=[OrderedStatistic(items_base=frozenset({'coffee'}), items_add=frozenset({'donut'}), confidence=0.8, lift=3.8095238095238098), OrderedStatistic(items_base=frozenset({'donut'}), items_add=frozenset({'coffee'}), confidence=0.9523809523809524, lift=3.8095238095238098)]),
 RelationRecord(items=frozenset({'coffee', 'sugar'}), support=0.09, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sugar'}), items_add=frozenset({'coffee'}), confidence=0.75, lift=3.0)]),
 RelationRecord(items=frozenset({'bread', 'jam', 'nan'}), support=0.08, ordered_statistics=[OrderedStatistic(items_base=frozenset({'jam'}), items_add=frozenset({'bread', 'nan'}), confidence=0.7999999999999999, lift=4.2105263157894735), OrderedStatistic(items_base=frozenset({'nan', 'jam'}), items_add=frozenset({'bread'}), confidence=0.7999999999999999, lift=3.8095238095238093)]),
 RelationRecord(items=frozenset({'nan', 'donut', 'coffee'}), support=0.17, ordered_statistics=[OrderedStatistic(items_base=frozenset({'donut'}), items_add=frozenset({'nan', 'coffee'}), confidence=0.8095238095238096, lift=3.8548752834467126), OrderedStatistic(items_base=frozenset({'nan', 'coffee'}), items_add=frozenset({'donut'}), confidence=0.8095238095238096, lift=3.8548752834467126), OrderedStatistic(items_base=frozenset({'nan', 'donut'}), items_add=frozenset({'coffee'}), confidence=0.9444444444444445, lift=3.777777777777778)])]

In [8]:
def inspect(results):
    li          = [tuple(result[2][0][0])[0] for result in results]
    ri          = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(li, ri, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Item', 'Right Item', 'Support', 'Confidence', 'Lift'])

In [9]:
resultsinDataFrame

  Left Item Right Item  Support  Confidence      Lift
0       jam      bread     0.08    0.800000  3.809524
1    coffee      donut     0.20    0.800000  3.809524
2     sugar     coffee     0.09    0.750000  3.000000
3       jam      bread     0.08    0.800000  4.210526
4     donut        nan     0.17    0.809524  3.854875